#!/bin/sh
while read file
do
        case "$1" in
	"s")
		[ -z "$savePath" ] && savePath="$(zenity --title="Save File" --file-selection --save --confirm-overwrite)"
		[ -z "$savePath" ] && exit
		mv "$file" "$savePath" && notify-send "$file saved to $savePath." &
		;;
        "c")
		[ -z "$destdir" ] && destdir="$(sed "/^#/d;/^$/d" ~/scripts/folders | awk '{print $2}' | rofi -i -dmenu -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		cp "$file" "$destdir" && notify-send "$file copied to $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(sed "/^#/d;/^$/d" ~/scripts/folders | awk '{print $2}' | rofi -i -dmenu -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		mv "$file" "$destdir" && notify-send "$file moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		echo -n "$(readlink -f "$file")" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | rofi -i -dmenu -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        esac
done
